services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    gpus: all
    env_file:
      - ../.env
      - /srv/secrets/litellm.env
    environment:
      - TZ=Asia/Tokyo
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    networks:
      - shared_network
      - ollama_default

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:8002:80"
    environment:
      - TZ=Asia/Tokyo
    networks:
      - shared_network

#   db:
#     image: postgres:16
#     profiles:
#       - db
#     env_file:
#       - ../.env
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
networks:
  shared_network:
    external: true
  ollama_default:
    external: true
