import React from 'react';
import { X, Sparkles, Bot } from 'lucide-react';
import { TechInsightResponse } from '../types';

interface TechInsightModalProps {
  isOpen: boolean;
  onClose: () => void;
  loading: boolean;
  data: TechInsightResponse | null;
  keyword: string | null;
}

export const TechInsightModal: React.FC<TechInsightModalProps> = ({ isOpen, onClose, loading, data, keyword }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full overflow-hidden scale-100 transition-all">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
          <div className="flex items-center gap-2 text-brand-700">
            <Sparkles className="w-5 h-5" />
            <h3 className="font-semibold">Tech Insight</h3>
          </div>
          <button onClick={onClose} className="p-1 rounded-full hover:bg-slate-200 text-slate-500 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 min-h-[200px] flex flex-col">
          {loading ? (
            <div className="flex-1 flex flex-col items-center justify-center gap-4 text-slate-500">
              <Bot className="w-10 h-10 animate-bounce text-brand-500" />
              <p className="text-sm font-medium">Generating insight for "{keyword}"...</p>
            </div>
          ) : data ? (
            <div className="animate-in slide-in-from-bottom-2 duration-300">
              <h4 className="text-2xl font-bold text-slate-800 mb-4">{data.keyword}</h4>
              <div className="prose prose-slate text-slate-600 leading-relaxed">
                {data.insight}
              </div>
              <div className="mt-6 pt-4 border-t border-slate-100 text-xs text-slate-400 flex items-center gap-1">
                <Bot className="w-3 h-3" />
                Generated by OpenAI Analysis
              </div>
            </div>
          ) : (
            <div className="flex-1 flex items-center justify-center text-red-500">
              <p>Failed to load insight. Please try again.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};